#!/usr/bin/env python3
"""Write /usr/share/doc/fermix-desktop/copyright, in Debian's machine-readable format, from what
the package is built from.

    copyright.py --repo <repository root> --lock <RUNTIME.lock.json>
                 --runtime-licenses <runtime-licenses.json>
                 --runtime-texts <runtime-licenses.tar.gz, unpacked>
                 --window-crates <window-crates.json> --vendored <vendored.json>
                 --standard-texts <dir> --engine-copyright <staged engine copyright> --out <file>

One paragraph each for this repository's own code (Files: *) and for every vendored part of it,
in vendored.json's order, so the more specific pattern comes later and wins. Then the runtime's
components, the crates compiled into the runtime, the Rust standard library, and the crates the
window's build compiles, each with its licence files' text as the runtime's licence archive or the
cargo registry holds it; parts whose licence and texts are the same share one paragraph. Then the
engine, which points to its own copyright file. Then a stand-alone License paragraph for each
LicenseRef a Files paragraph names, holding the one text runtime-licenses.json's license_refs maps
it to, which the component's paragraph then leaves out; and the text of MIT for the paragraphs
that state no text of their own.

runtime-licenses.json must account for every component of the lock, with the lock's version and
licence. A build-only component, such as a set of protocol files the build reads, ships nothing
and has no paragraph. Its license_refs must map every LicenseRef any expression names, and map no
other.

A crate that ships no licence file is given the standard text of each licence its expression
names, from <standard-texts>/<id>.txt, which are SPDX license-list-data v3.29.0's texts.
desktop/scripts/check_copyright.sh holds a copyright file to this program's output and to its
inputs.
"""

import argparse
import json
import os
import re
import sys
import textwrap

FORMAT = "https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/"
WIDTH = 99
OPERATORS = {"OR", "AND", "WITH"}
LICENSE_REF = re.compile(r"LicenseRef-[A-Za-z0-9.-]+")
HEADER_COMMENT = (
    "Generated by desktop/packaging/copyright.py from the private runtime's lock file and licence "
    "lists, the crates cargo compiles into the window, and desktop/packaging/vendored.json. "
    "desktop/scripts/check_copyright.sh refuses a copy that disagrees with them.",
    "Files patterns name the source each part is built from: * and desktop/ are this "
    "repository; crates/<name>-<version>/ is a crate the window's build compiles; "
    "runtime/<name>-<version>/ is a component of the private runtime under "
    "/usr/lib/fermix-desktop, built from the tarball its comment names, "
    "runtime/crates/<name>-<version>/ a crate compiled into one of those components, and "
    "runtime/rust-std-<version>/ the Rust standard library; engine/ is the engine. "
    "Licence expressions are SPDX expressions.",
)
LGPL_NOTE = (
    "The package carries this library as a shared object in /usr/lib/fermix-desktop/lib, which "
    "the window finds through the RUNPATH $ORIGIN/../lib and through no environment variable. A "
    "person exercising their rights under the LGPL may replace the file with their own build of "
    "the same SONAME in that directory, and the window loads it with nothing relinked."
)
OWN_NOTE = (
    "The window, /usr/lib/fermix-desktop/bin/fermix-desktop, "
    "reached through /usr/bin/fermix-desktop. "
    "Its resource bundle carries vendor marks, each the vendor's own and unmodified; "
    "desktop/app/marks/PROVENANCE.json records where each comes from and the terms it is used on."
)
ENGINE_NOTE = (
    "The engine: /usr/bin/fermix and every other file the fermix package installs, as that "
    "package installs them, unchanged. Its own copyright file, which lists every component the "
    "engine bundles, is /usr/share/doc/fermix/copyright."
)
USAGE = (
    "copyright.py --repo <dir> --lock <file> --runtime-licenses <file> --runtime-texts <dir> "
    "--window-crates <file> --vendored <file> --standard-texts <dir> --engine-copyright <file> "
    "--out <file>"
)


class Refusal(Exception):
    """A refusal; its message is the sentence printed after "copyright: "."""


class Parser(argparse.ArgumentParser):
    """argparse, refusing a malformed command line the way every other mistake here is refused."""

    def error(self, message):
        raise Refusal(f"usage: {USAGE} ({message})")


def read_text(path):
    try:
        with open(path, encoding="utf-8") as handle:
            return handle.read()
    except OSError as error:
        raise Refusal(f"cannot read {path}: {error.strerror}") from error
    except UnicodeDecodeError as error:
        raise Refusal(f"{path} is not UTF-8 text: {error}") from error


def read_json(path):
    try:
        return json.loads(read_text(path))
    except ValueError as error:
        raise Refusal(f"{path} is not valid JSON: {error}") from error


def part(patterns, licence, copyright_lines, texts, notes):
    """One licensed part: Files patterns, licence, holders, licence texts, comment sentences."""
    return {"patterns": patterns, "license": licence, "copyright": copyright_lines,
            "texts": texts, "notes": notes}  # fmt: skip


def licence_ids(expression):
    return [t for t in re.findall(r"[A-Za-z0-9.+-]+", expression) if t not in OPERATORS]


def standard_texts(expression, standard_dir, who):
    texts = []
    for identifier in licence_ids(expression):
        path = os.path.join(standard_dir, f"{identifier}.txt")
        if not os.path.isfile(path):
            raise Refusal(f"{who} ships no licence file, and there is no standard text {path}")
        texts.append(read_text(path))
    return texts


def excerpt(repo, spec):
    lines = read_text(os.path.join(repo, spec["file"])).splitlines()
    chosen = lines[spec["first_line"] - 1 : spec["last_line"]]
    prefix = spec["strip_prefix"]
    stripped = [line[len(prefix) :] if line.startswith(prefix) else line for line in chosen]
    return "\n".join(line[1:] if line.startswith(" ") else line for line in stripped) + "\n"


def vendored_parts(repo, vendored, standard_dir):
    parts = []
    for entry in vendored["vendored"]:
        texts = [read_text(os.path.join(repo, s["file"])) if "first_line" not in s
                 else excerpt(repo, s) for s in entry["texts"]]  # fmt: skip
        if not texts:
            texts = standard_texts(entry["license"], standard_dir, entry["name"])
        parts.append(part(entry["files"], entry["license"], entry["copyright"], texts,
                          [entry["comment"]]))  # fmt: skip
    return parts


def archive_texts(texts_dir, paths, who):
    texts = []
    for relative in paths:
        path = os.path.join(texts_dir, relative)
        if not os.path.isfile(path):
            raise Refusal(f"the runtime's licence archive has no {relative}, which {who} names")
        texts.append(read_text(path))
    return texts


def accounted_components(lock, licenses):
    """The lock's components, each with its runtime-licenses.json entry, which must agree."""
    listed = {(c["name"], c["version"]): c for c in licenses["components"]}
    locked = {(c["name"], c["version"]) for c in lock["components"]}
    extra = sorted(set(listed) - locked)
    if extra:
        raise Refusal(f"runtime-licenses.json has the component {' '.join(extra[0])}, "
                      "which the lock does not")  # fmt: skip
    pairs = []
    for component in lock["components"]:
        who = f"{component['name']} {component['version']}"
        entry = listed.get((component["name"], component["version"]))
        if entry is None:
            raise Refusal(f"the lock's component {who} is not in runtime-licenses.json")
        if entry["license"] != component["license"]:
            raise Refusal(f"the lock gives {who} the licence {component['license']}, "
                          f"and runtime-licenses.json {entry['license']}")  # fmt: skip
        pairs.append((component, entry))
    return pairs


def licence_refs(licenses):
    refs = licenses.get("license_refs")
    if not isinstance(refs, dict):
        raise Refusal("runtime-licenses.json has no license_refs object")
    return refs


def accounted_refs(refs, expressions):
    """Each LicenseRef the (who, expression) pairs name is mapped, and each one mapped is named."""
    named = set()
    for who, expression in expressions:
        for ref in LICENSE_REF.findall(expression):
            if ref not in refs:
                raise Refusal(f"{who}'s licence names {ref}, which runtime-licenses.json's "
                              "license_refs does not map")  # fmt: skip
            named.add(ref)
    unused = sorted(set(refs) - named)
    if unused:
        raise Refusal(f"runtime-licenses.json's license_refs maps {unused[0]}, "
                      "which no licence names")  # fmt: skip


def expressions(licenses, window_crates, vendored):
    """Every licence expression of the inputs, with whose it is."""
    pairs = [(f"{c['name']} {c['version']}", c["license"]) for c in licenses["components"]]
    pairs += [(f"{c['name']} {c['version']}", c["license"]) for c in licenses["crates"]]
    std = licenses["rust_std"]
    pairs.append((f"the Rust standard library {std['version']}", std["license"]))
    pairs += [(f"{c['name']} {c['version']}", c["license"]) for c in window_crates["crates"]]
    return pairs + [(entry["name"], entry["license"]) for entry in vendored["vendored"]]


def component_parts(lock, licenses, texts_dir):
    """The shipped components, each with its licence files but those a LicenseRef stands for."""
    parts = []
    mapped = set(licence_refs(licenses).values())
    for component, entry in accounted_components(lock, licenses):
        if entry["build_only"]:
            continue
        who = f"{component['name']} {component['version']}"
        if not entry["license_files"]:
            raise Refusal(f"runtime-licenses.json lists no licence files for {who}")
        notes = [f"{who}, built from {component['url']}, sha256 {component['sha256']}."]
        if "LGPL" in component["license"]:
            notes.append(LGPL_NOTE)
        files = [path for path in entry["license_files"] if path not in mapped]
        texts = archive_texts(texts_dir, files, who)
        parts.append(part([f"runtime/{component['name']}-{component['version']}/*"],
                          component["license"], [f"The {component['name']} authors"], texts,
                          notes))  # fmt: skip
    return parts


def cargo_licence(expression):
    """A crate's licence as SPDX: Cargo's deprecated "/" means OR, as window_crates.py reads it."""
    return " OR ".join(part.strip() for part in expression.split("/"))


def runtime_crate_parts(licenses, texts_dir, standard_dir):
    parts = []
    for crate in licenses["crates"]:
        who = f"{crate['name']} {crate['version']}"
        licence = cargo_licence(crate["license"])
        texts = archive_texts(texts_dir, crate["license_files"], who)
        notes = [f"{who}, compiled into the private runtime."]
        if not texts:
            texts = standard_texts(licence, standard_dir, who)
            notes.append(f"{who} ships no licence file; its text is the licence's standard one.")
        parts.append(part([f"runtime/crates/{crate['name']}-{crate['version']}/*"], licence,
                          [f"The {crate['name']} authors"], texts, notes))  # fmt: skip
    return parts


def rust_std_part(licenses, texts_dir):
    std = licenses["rust_std"]
    who = f"the Rust standard library {std['version']}"
    if not std["license_files"]:
        raise Refusal(f"runtime-licenses.json lists no licence files for {who}")
    note = (f"The Rust standard library {std['version']}, which the runtime's Rust code and the "
            "window link.")  # fmt: skip
    texts = archive_texts(texts_dir, std["license_files"], who)
    return part([f"runtime/rust-std-{std['version']}/*"], std["license"],
                ["The Rust Project Developers"], texts, [note])  # fmt: skip


def window_crate_parts(window_crates, standard_dir):
    parts = []
    for crate in window_crates["crates"]:
        who = f"{crate['name']} {crate['version']}"
        texts = [f["text"] for f in crate["files"]]
        notes = [f"{who}, compiled into the window."]
        if not crate["linked"]:
            notes = [f"{who} runs while the window is built, as a build script, a "
                     "procedural macro or what one of those needs; none of it is linked into "
                     "the window."]  # fmt: skip
        if not texts:
            texts = standard_texts(crate["license"], standard_dir, who)
            notes.append(f"{who} ships no licence file; its text is the licence's standard one.")
        holders = crate["authors"] or [f"The {crate['name']} authors"]
        parts.append(part([f"crates/{crate['name']}-{crate['version']}/*"], crate["license"],
                          holders, texts, notes))  # fmt: skip
    return parts


def merged(parts):
    """Parts with one licence and the same texts, as one paragraph each, in pattern order."""
    groups = {}
    for item in parts:
        key = (item["license"], tuple(item["texts"]))
        if key not in groups:
            groups[key] = part([], item["license"], [], item["texts"], [])
        group = groups[key]
        group["patterns"] += item["patterns"]
        group["copyright"] += [h for h in item["copyright"] if h not in group["copyright"]]
        group["notes"] += [n for n in item["notes"] if n not in group["notes"]]
    return sorted(groups.values(), key=lambda g: g["patterns"][0])


def text_lines(text):
    lines = [line.rstrip() for line in text.rstrip().splitlines()]
    return [f" {line}" if line else " ." for line in lines]


def comment_lines(notes):
    lines = []
    for index, note in enumerate(notes):
        if index:
            lines.append(" .")
        wrapped = textwrap.wrap(note, WIDTH, break_long_words=False, break_on_hyphens=False)
        lines += [f" {line}" for line in wrapped]
    return lines


def paragraph(item):
    lines = [f"Files: {' '.join(item['patterns'])}", f"Copyright: {item['copyright'][0]}"]
    lines += [f"           {holder}" for holder in item["copyright"][1:]]
    lines.append(f"License: {item['license']}")
    for index, text in enumerate(item["texts"]):
        lines += ([" ."] if index else []) + text_lines(text)
    if item["notes"]:
        lines += ["Comment:"] + comment_lines(item["notes"])
    return "\n".join(lines)


def ref_note(path):
    source = path.removeprefix("components/")
    if source.endswith(".notice"):
        return f"The notice in {source.removesuffix('.notice')} of the private runtime's sources."
    return f"The text of {source} in the private runtime's sources."


def ref_paragraphs(refs, parts, texts_dir):
    """A stand-alone License paragraph for each LicenseRef the paragraphs name, with its text."""
    used = sorted({ref for item in parts for ref in LICENSE_REF.findall(item["license"])})
    paragraphs = []
    for ref in used:
        text = archive_texts(texts_dir, [refs[ref]], ref)[0]
        note = comment_lines([ref_note(refs[ref])])
        lines = [f"License: {ref}", *text_lines(text), "Comment:", *note]
        paragraphs.append("\n".join(lines))
    return paragraphs


def header():
    lines = [f"Format: {FORMAT}", "Upstream-Name: fermix-desktop",
             "Upstream-Contact: Tezra <hello@fermix.ai>",
             "Source: https://github.com/tezra-io/fermix-linux", "Comment:"]  # fmt: skip
    return "\n".join(lines + comment_lines(HEADER_COMMENT))


def document(arguments):
    if not os.path.isfile(arguments.engine_copyright):
        raise Refusal(f"there is no engine copyright file at {arguments.engine_copyright}")
    standard, texts = arguments.standard_texts, arguments.runtime_texts
    lock, licenses = read_json(arguments.lock), read_json(arguments.runtime_licenses)
    window_crates, vendored = read_json(arguments.window_crates), read_json(arguments.vendored)
    refs = licence_refs(licenses)
    accounted_refs(refs, expressions(licenses, window_crates, vendored))
    own = part(["*"], "MIT", ["Tezra"], [], [OWN_NOTE])
    shared = (component_parts(lock, licenses, texts)
              + runtime_crate_parts(licenses, texts, standard)
              + [rust_std_part(licenses, texts)]
              + window_crate_parts(window_crates, standard))  # fmt: skip
    engine = part(["engine/*"], "MIT", ["Tezra"], [], [ENGINE_NOTE])
    files = [own, *vendored_parts(arguments.repo, vendored, standard), *merged(shared), engine]
    repo_licence = read_text(os.path.join(arguments.repo, "LICENSE"))
    mit = "License: MIT\n" + "\n".join(text_lines(repo_licence))
    paragraphs = [header()] + [paragraph(p) for p in files]
    return "\n\n".join([*paragraphs, *ref_paragraphs(refs, files, texts), mit]) + "\n", len(files)


def write(path, text):
    partial = f"{path}.partial"
    with open(partial, "w", encoding="utf-8") as handle:
        handle.write(text)
    os.replace(partial, path)


def parse_arguments(argv):
    parser = Parser(prog="copyright.py", add_help=False)
    for name in ("repo", "lock", "runtime-licenses", "runtime-texts", "window-crates",
                 "vendored", "standard-texts", "engine-copyright", "out"):  # fmt: skip
        parser.add_argument(f"--{name}", required=True)
    return parser.parse_args(argv)


def main(argv):
    try:
        arguments = parse_arguments(argv)
        text, count = document(arguments)
        write(arguments.out, text)
    except Refusal as refusal:
        print(f"copyright: {refusal}", file=sys.stderr)
        return 1
    print(f"copyright: {arguments.out}, {count} Files paragraphs, {len(text)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
