#!/usr/bin/env python3
"""Write packaging/copyright from the runtime lock file.

Amendment section 4.6. The package carries twenty-nine third-party libraries
that a distribution would otherwise have packaged, each with its own licence,
and most of them under the LGPL. A copyright file maintained by hand is a
copyright file that is wrong the first time a component is added, which is the
failure this generator exists to remove: the lock file is the one list, and this
file is derived from it.

Three things every stanza carries, because all three are obligations rather than
courtesies:

  * the component's version and the exact source tarball it was built from, by
    URL and by sha256, which is the written offer of LGPL 2.1 section 3
    honoured by a link;
  * its licence identifier, and the full text of that licence in a standalone
    paragraph below;
  * for the LGPL components, the sentence that says how a person exercises
    section 6: the libraries are shared objects in a directory the application
    finds through `RUNPATH`, so a replacement of the same SONAME in that
    directory is loaded with no relinking and no environment variable.

The licence texts are not written here and are not recalled. Each one is a file
under `packaging/licenses/`, taken from the component's own source tarball or
from `/usr/share/common-licenses`, and the file name is the licence expression
the lock file declares. A component whose expression has no text file is a
refusal rather than a stanza with a gap in it.

Usage:
  generate_copyright.py --lock <RUNTIME.lock.json> --licenses <dir> --out <path>
  generate_copyright.py ... --check      write nothing, refuse if <path> differs
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PREFIX = "/usr/lib/fermix-desktop"

HEADER = """Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: fermix-desktop
Upstream-Contact: Tezra <hello@fermix.ai>
Source: https://github.com/tezra-io/fermix-linux
Comment:
 This file is generated by scripts/generate_copyright.py from
 packaging/runtime/RUNTIME.lock.json and the licence texts in
 packaging/licenses/. Do not edit it by hand: scripts/check_copyright.sh
 regenerates it and refuses any difference, which is what stops a bundled
 component from being added without its licence.
 .
 The package installs three kinds of thing. The window is this project's own
 code. The private toolkit runtime under {prefix} is the
 third-party libraries below, each built from the source tarball its stanza
 names. The engine under /usr/bin/fermix and /usr/lib/fermix is a separate
 build with its own copyright file at /usr/share/doc/fermix/copyright.
 .
 /usr/share/doc/fermix-desktop/runtime-manifest.json records every one of the
 components below together with the sha256 of every file it installed, so the
 list here is answerable from an installed machine rather than only from this
 repository.
""".format(prefix=PREFIX)

APPLICATION = """
Files: *
Copyright: Tezra
License: MIT
Comment:
 /usr/lib/fermix-desktop/bin/fermix-desktop is a Rust executable, reached
 through the symbolic link /usr/bin/fermix-desktop. Statically linked into it
 are this project's own code and the Rust crates it depends on, each under its
 own licence, all of them MIT or Apache License 2.0; Cargo.lock names every
 one. It links the toolkit below dynamically.
 .
 The executable also carries one compiled resource bundle, whose contents are:
 .
   * The application icon and its symbolic pair, and the Fermix mascot and
     wordmark. Tezra's own artwork, MIT License with this package.
   * Vendor marks for the providers, channels, plugins, sign-in clients and
     meeting platforms the application draws rows for. Each file is the
     vendor's own, redistributed unmodified under that vendor's brand terms;
     App/Fermix/resources/VendorMarks/PROVENANCE.json records the source, the
     retrieval date, the usage terms and the permitted treatment of every one
     of them, and no mark is recoloured, redrawn or invented.
   * One stylesheet, which sets no colour and no font.
"""

RELINKING = """ This library is carried by the package as a shared object in
 {prefix}/lib. The application finds it through the RUNPATH
 $ORIGIN/../lib recorded in the executable, and through no environment
 variable, so a person exercising their rights under LGPL 2.1 section 6 may
 replace the file with their own build of the same SONAME in that directory and
 the application will load it, with no relinking and nothing else to change.
""".format(prefix=PREFIX)

MIT_TEXT_NAME = "MIT"


class Refusal(RuntimeError):
    """Something the generator will not paper over, phrased for a person."""


def licence_file(directory: Path, expression: str) -> Path:
    """The text for one licence expression, named after the expression itself."""
    return directory / (expression.replace(" ", "_") + ".txt")


def read_licence(directory: Path, expression: str) -> str:
    path = licence_file(directory, expression)
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise Refusal(
            f"the lock file declares the licence '{expression}' and there is no text "
            f"for it at {path}: add the licence's own text from the component's "
            f"source tarball"
        ) from error


def indent(text: str) -> str:
    """A licence text as one Debian machine-readable paragraph.

    An empty line inside a field is written as a single dot, and every line is
    prefixed with one space. A line that already begins with a dot is escaped,
    which the format requires and which a licence text does contain.
    """
    lines = []
    for line in text.rstrip("\n").split("\n"):
        stripped = line.rstrip()
        if not stripped:
            lines.append(" .")
        elif stripped.startswith("."):
            lines.append(" ." + stripped)
        else:
            lines.append(" " + stripped)
    return "\n".join(lines)


def component_stanza(component: dict) -> str:
    """One `Files:` stanza for one bundled component."""
    for field in ("name", "version", "url", "sha256", "license"):
        if not component.get(field):
            raise Refusal(
                f"a lock file component carries no {field}: {component.get('name', component)!r}"
            )

    name = component["name"]
    body = [
        f"Files: {PREFIX}/*",
        f"Copyright: The {name} authors",
        f"License: {component['license']}",
        "Comment:",
        f" {name} {component['version']}, built from",
        f" {component['url']}",
        f" sha256 {component['sha256']}",
    ]
    if component["license"].startswith("LGPL"):
        body.append(" .")
        body.append(RELINKING.rstrip("\n"))
    return "\n".join(body) + "\n"


def render(lock: dict, licenses: Path) -> str:
    components = lock.get("components")
    if not isinstance(components, list) or not components:
        raise Refusal("the lock file declares no components at all")

    pieces = [HEADER, APPLICATION]
    for component in components:
        pieces.append("\n" + component_stanza(component))

    # One standalone paragraph per distinct expression, in the order a reader
    # meets them, so a stanza's `License:` line always has a text below it.
    seen: list[str] = [MIT_TEXT_NAME]
    for component in components:
        if component["license"] not in seen:
            seen.append(component["license"])

    for expression in seen:
        text = read_licence(licenses, expression)
        pieces.append(f"\nLicense: {expression}\n{indent(text)}\n")

    return "".join(pieces)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lock", required=True, type=Path)
    parser.add_argument("--licenses", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; refuse if --out is not what this would write",
    )
    arguments = parser.parse_args(argv)

    try:
        try:
            lock = json.loads(arguments.lock.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise Refusal(f"cannot read the lock file {arguments.lock}: {error}") from error
        if not arguments.licenses.is_dir():
            raise Refusal(f"no licence texts at {arguments.licenses}")
        rendered = render(lock, arguments.licenses)
    except Refusal as refusal:
        print(f"generate_copyright: {refusal}", file=sys.stderr)
        return 1

    if arguments.check:
        try:
            current = arguments.out.read_text(encoding="utf-8")
        except OSError as error:
            print(f"generate_copyright: cannot read {arguments.out}: {error}", file=sys.stderr)
            return 1
        if current != rendered:
            print(
                f"generate_copyright: {arguments.out} is not what the lock file and the "
                "licence texts render; run scripts/generate_copyright.py to rewrite it",
                file=sys.stderr,
            )
            return 1
        print(f"  {arguments.out.name} is what the lock file renders")
        return 0

    arguments.out.write_text(rendered, encoding="utf-8")
    print(f"generate_copyright: wrote {arguments.out} from {arguments.lock}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
